# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b67d23c62dff73828a0402509d671a520926ddc10b591543934f1506c3ea6e6e64d192d87c5ce98c1938baa350795d016fedd322c5fa4e657a6f84e2308a47e

test:
  secret_key_base: c1c9bbd21e95bd5f7291d5cebbc5d7efebbacfdc813609486c59ab7fe3a5eb1d83a00c33fc7e3b485a59caecd7d3e0cf98db4bd3509ea0ea8074c4b0c98b8cb2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
